### ISSUE TITLE
Issue With Favorites

### ISSUE THREAD

**Issue by SamuelBanya** [crtpi/CRTPi-Project#2]
Hey there,

I have an issue in which I can save favorites, but upon restarting this build with a reboot of the Pi, the favorites list doesn't seem to save.

Is this something I can fix with permissions in a specific directory perhaps?

Or is this tied to the gamelist.xml files? Curious for your thoughts thanks!

**Comment by stuckonretro** [comment]
Typically, you have to do a clean shutdown or restart emulationstation to make changes to the gameslists to stick. I prefer the latter, just going into the ES menu and choosing to restart/reboot emulationstation from the list. 

If that doesn't work, try the resetting permissions from the retropie-setup menu and then marking favorites, then restarting ES.

**Comment by SamuelBanya** [comment]
Yep that worked thanks!
